### ISSUE TITLE
你好作者大大，打卡经常报错

### ISSUE THREAD

**Issue by liangw1024** [zycn0910/Sign-ZXJY#20]
Traceback (most recent call last):
  File "Main.py", line 80, in <module>
    sign_main(users)
  File "Main.py", line 23, in sign_main
    info = process.login_and_sign_in(user=user, endday=TDOA.days)
  File "/www/wwwroot/szx/Sign-ZXJY/process.py", line 157, in login_and_sign_in
    login_token = get_Apitoken()
  File "/www/wwwroot/szx/Sign-ZXJY/process.py", line 23, in get_Apitoken
    response = requests.post(url, headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

**Comment by zycn0910** [comment]
换个网络稳定的设备运行吧

**Comment by juzhige2018** [comment]
1.请检查网络环境
2.请检查json文件保存格式为UTF-8而不是UTF-8 For ROM或者GBK2312
