### ISSUE TITLE
你好作者，报错如下，报错有办法跳过吗requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=443): Read timed out. (read timeout=5)

### ISSUE THREAD

**Issue by liangw1024** [zycn0910/Sign-ZXJY#28]
系统平台：centos

问题详细描述：反馈超时

终端报错输出：Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 642, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 783, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 471, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 515, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1114: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 470, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 371, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=443): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 53, in <module>
    main(process.load_users_from_json("all-users.json"))
  File "Main.py", line 28, in main
    info = process.login_and_sign_in(user=user, endday=TDOA.days)
  File "/www/shixi/zx/process.py", line 296, in login_and_sign_in
    sign_in_response = sign_in_request(uid, user['address'], user['deviceId'], 0, user['longitude'],
  File "/www/shixi/zx/process.py", line 240, in sign_in_request
    response_text = send_request(url=url, method='POST', headers=header, data=data, proxy=proxy_data)
  File "/www/shixi/zx/process.py", line 175, in send_request
    response = requests.post(url=url, headers=headers, data=json.dumps(data),
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=443): Read timed out. (read timeout=5)

日志（config.py文件log_report改为True）：

**Comment by zycn0910** [comment]
网络问题

**Comment by zycn0910** [comment]
取消使用代理试试

**Comment by xiaizizi** [comment]
Traceback (most recent call last):
  File "d:\文件\桌面\刷机\4\Sign-ZXJY-master\Main.py", line 7, in <module>
    import process
  File "d:\文件\桌面\刷机\4\Sign-ZXJY-master\process.py", line 12, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
11月21号报错

**Comment by xiaizizi** [comment]
> Traceback (most recent call last): File "d:\文件\桌面\刷机\4\Sign-ZXJY-master\Main.py", line 7, in import process File "d:\文件\桌面\刷机\4\Sign-ZXJY-master\process.py", line 12, in from bs4 import BeautifulSoup ModuleNotFoundError: No module named 'bs4' 11月21号报错

这个解决了
删除了那个bs4可以运行了
