### ISSUE TITLE
你好作者大大，运行AddUser-noinput.py出错，求解答

### ISSUE THREAD

**Issue by zzy1286709952** [zycn0910/Sign-ZXJY#32]
系统平台（Windows、Linux、云函数）：liunx（青龙面板）

config.py内开启了什么功能：无

问题详细描述（怎么发现的问题）：在定时任务中运行AddUser-noinput.py出错

终端报错输出（最后几行即可）：## 开始执行... 2023-12-12 11:20:58

Traceback (most recent call last):
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/AddUser-noinput.py", line 122, in <module>
    name = json.loads(get_account_data(device, phone, password))['data']['uname']
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/process.py", line 287, in get_account_data
    uid = user_data['data']['uid']
KeyError: 'uid'

## 执行结束... 2023-12-12 11:20:59  耗时 1 秒　　　　　

日志（config.py内log改为Tru后，在log文件夹下查看）：无

**Comment by zzy1286709952** [comment]
![微信截图_20231217201449](https://github.com/zycn0910/Sign-ZXJY/assets/96131583/fcd277c3-8912-43c5-bcb1-09364fa47bed)
这个是log日志

**Comment by zzy1286709952** [comment]
![微信截图_20231217201449](https://github.com/zycn0910/Sign-ZXJY/assets/96131583/fcd277c3-8912-43c5-bcb1-09364fa47bed)
这个是log日志

**Comment by zzy1286709952** [comment]
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): sxbaapp.zcj.jyt.henan.gov.cn:80 - connectionpool.py - _new_conn - 244
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - http://sxbaapp.zcj.jyt.henan.gov.cn:80 "POST /api/getApitoken.ashx HTTP/1.1" 200 279 - connectionpool.py - _make_request - 546
2023-12-12 11:43:41 - root - INFO - YcT3mukklI9uHckTU30XVx4CkmjGsBej0GOrujFQy7U= - process.py - get_Apitoken - 170
2023-12-12 11:43:41 - root - INFO - <hmac.HMAC object at 0x7f9164a8a520> - process.py - calculate_hmac_sha256 - 112
2023-12-12 11:43:41 - root - INFO - abe3f7edec3776420d8cfb39582ecf1f10216dec248f26fb137c3a1818ac3e61 - process.py - calculate_sign - 231
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): apps.apple.com:443 - connectionpool.py - _new_conn - 1052
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - https://apps.apple.com:443 "GET /us/app/%E8%81%8C%E6%A0%A1%E5%AE%B6%E5%9B%AD/id1606842290 HTTP/1.1" 200 None - connectionpool.py - _make_request - 546
2023-12-12 11:43:41 - root - INFO - {'Accept': '*/*', 'timestamp': '1702352621398', 'os': 'ios', 'Accept-Encoding': 'gzip, deflate, br', 'Accept-Language': 'zh-Hans-CN;q=1', 'Content-Type': 'application/json', 'User-Agent': 'Internship/1.3.8 (iPhone; iOS 16.6; Scale/3.00)', 'Connection': 'keep-alive', 'phone': 'iPhone14 Pro', 'token': 'YcT3mukklI9uHckTU30XVx4CkmjGsBej0GOrujFQy7U=', 'sign': 'abe3f7edec3776420d8cfb39582ecf1f10216dec248f26fb137c3a1818ac3e61', 'appVersion': '1.4.3'} - process.py - generate_headers - 155
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): sxbaapp.zcj.jyt.henan.gov.cn:80 - connectionpool.py - _new_conn - 244
2023-12-12 11:43:41 - urllib3.connectionpool - DEBUG - http://sxbaapp.zcj.jyt.henan.gov.cn:80 "POST /api/relog.ashx HTTP/1.1" 200 229 - connectionpool.py - _make_request - 546
2023-12-12 11:43:41 - root - INFO - {"code":1002,"deviceId":"","data":{},"msg":"错误代码：20081","currentpage":0,"pagesize":0,"totalcount":0,"pagecount":0} - process.py - login_request - 247
2023-12-12 11:43:41 - root - INFO - {"code":1002,"deviceId":"","data":{},"msg":"错误代码：20081","currentpage":0,"pagesize":0,"totalcount":0,"pagecount":0} - process.py - get_user_uid - 281


这个是log日志

**Comment by zycn0910** [comment]
哥们，你是不是把职校家园的密码输错了

**Comment by zycn0910** [comment]
还有，建议使用python3.9以上的青龙面板，或者删除process.py里20行encoding="utf-8"参数

**Comment by zzy1286709952** [comment]
账号密码没有错，删除 process.py里29行encoding="utf-8"参数后 AddUser-noinput.py脚本变为一直运行状态了

**Comment by zzy1286709952** [comment]
## 开始执行... 2023-12-12 12:36:13

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 212, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9ba24652a0>, 'Connection to sxbaapp.zcj.jyt.henan.gov.cn timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=80): Max retries exceeded with url: /api/getApitoken.ashx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9ba24652a0>, 'Connection to sxbaapp.zcj.jyt.henan.gov.cn timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/AddUser-noinput.py", line 122, in <module>
    name = json.loads(get_account_data(device, phone, password))['data']['uname']
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/process.py", line 286, in get_account_data
    user_data = json.loads(get_user_uid(deviceId, phone, password))
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/process.py", line 277, in get_user_uid
    login_token = get_Apitoken()
  File "/ql/data/scripts/zycn0910_Sign-ZXJY/process.py", line 165, in get_Apitoken
    response = requests.post(url, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='sxbaapp.zcj.jyt.henan.gov.cn', port=80): Max retries exceeded with url: /api/getApitoken.ashx (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9ba24652a0>, 'Connection to sxbaapp.zcj.jyt.henan.gov.cn timed out. (connect timeout=None)'))

## 执行结束... 2023-12-12 12:38:20  耗时 127 秒

**Comment by zycn0910** [comment]
encoding前有个逗号也要删除，另外看看报错信息，还有40081代码就是账号密码错了

**Comment by zzy1286709952** [comment]
我再试试，麻烦您了

**Comment by zzy1286709952** [comment]
已经成功可以运行了，谢谢作者大大
